[Setup]
AppName=FixBug
AppVersion=1.0.0
AppPublisher="Bharathikannan R"
DefaultDirName={autopf}\FixBug
DefaultGroupName=FixBug
OutputDir=Output
OutputBaseFilename=FixBug_Installer
Compression=lzma
SolidCompression=yes
; Required to immediately refresh the terminal environment variables after installation
ChangesEnvironment=yes
SetupIconFile=assets\fixbug.ico
UninstallDisplayIcon={app}\FixBug.exe

[Files]
; Packages the main executable
Source: "dist\FixBug\FixBug.exe"; DestDir: "{app}"; Flags: ignoreversion
; Packages all dependent DLLs, tree-sitter binaries, and cfonts data generated by PyInstaller
Source: "dist\FixBug\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{group}\FixBug"; Filename: "{app}\FixBug.exe"

[Registry]
; Adds the installation directory to the system PATH so 'fixbug' can be executed globally in the terminal
Root: HKCU; Subkey: "Environment"; ValueType: expandsz; ValueName: "Path"; ValueData: "{olddata};{app}"; Check: NeedsAddPath(ExpandConstant('{app}'))

[Code]
function NeedsAddPath(Param: string): boolean;
var
  OrigPath: string;
begin
  if not RegQueryStringValue(HKEY_CURRENT_USER, 'Environment', 'Path', OrigPath)
  then begin
    Result := True;
    exit;
  end;
  { Prevent duplicating the PATH entry if the user reinstalls or updates }
  Result := Pos(';' + Param + ';', ';' + OrigPath + ';') = 0;
end;