[Setup]
AppName=FixBug
AppVersion=1.0
AppPublisher=Bharathikannan R
DefaultDirName={autopf}\FixBug
DefaultGroupName=FixBug
OutputBaseFilename=FixBug_Installer
Compression=lzma
SolidCompression=yes
; This tells Windows to refresh the environment variables after installation
ChangesEnvironment=yes
PrivilegesRequired=lowest

[Files]
; Pulls the executable generated by PyInstaller
Source: "dist\fixbug.exe"; DestDir: "{app}"; Flags: ignoreversion

[Registry]
; Appends the installation directory to the User PATH environment variable
Root: HKCU; Subkey: "Environment"; ValueType: expandsz; ValueName: "Path"; ValueData: "{olddata};{app}"; Check: NeedsAddPath(ExpandConstant('{app}'))

[Code]
// Function to check if the path is already in the system environment to prevent duplicates
function NeedsAddPath(Param: string): boolean;
var
  OrigPath: string;
begin
  if not RegQueryStringValue(HKEY_CURRENT_USER, 'Environment', 'Path', OrigPath)
  then begin
    Result := True;
    exit;
  end;
  // Pos() returns 0 if the string is not found
  Result := Pos(';' + Param + ';', ';' + OrigPath + ';') = 0;
end;
